### ISSUE TITLE
youtube-dl addon doesnt work

### ISSUE THREAD

**Issue by benek984** [einschmidt/hassio-addons#40]
Just installed your addon but it doesn't work. See logs below:

````
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] scripts: applying... 
[fix-attrs.d] scripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: youtube-dl
 Download videos from youtube.com and a few more sites
-----------------------------------------------------------
 Add-on version: 0.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] global_config.sh: executing... 
INFO: Create global configuration file
INFO: -o /share/youtube-dl/%(title)s.%(ext)s
[cont-init.d] global_config.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Starting youtube-dl...
INFO: Starting in STDIN_mode...
INFO: Received URL: https://www.youtube.com/watch?v=7wfYIMyS_dI
NOTICE: No options found
INFO: Run: youtube-dl https://www.youtube.com/watch?v=7wfYIMyS_dI
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
INFO: STDIN service was stopped, restarting...
INFO: Starting youtube-dl...
INFO: Starting in STDIN_mode...
INFO: Received URL: https://www.youtube.com/watch?v=7wfYIMyS_dI
NOTICE: No options found
INFO: Run: youtube-dl https://www.youtube.com/watch?v=7wfYIMyS_dI
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
INFO: STDIN service was stopped, restarting...
INFO: Starting youtube-dl...
INFO: Starting in STDIN_mode...
INFO: Received URL: https://www.youtube.com/watch?v=7wfYIMyS_dI
NOTICE: No options found
INFO: Run: youtube-dl https://www.youtube.com/watch?v=7wfYIMyS_dI
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
INFO: STDIN service was stopped, restarting...
INFO: Starting youtube-dl...
INFO: Starting in STDIN_mode...
````a

**Comment by einschmidt** [comment]
Hi @benek984
It was kinda surprising to me, but I had the same finding as you shared.

However, in an attempt to apply a quick fix, I just noticed that youtube-dl is unmaintained for a while.
For the same reason I decided to archive the matching add-on. At the same time, it means I won't provide a fix for your finding.

Maybe another add-on exists somewhere, using a follow-up project.

Good luck, and thanks for reporting.
